
TIMEOUT: 3
INTERFACE_BRANDING: Equinox OS
INTERFACE_RESOLUTION: 1280x720
INTERFACE_BACKGROUND: boot():/res/BG.BMP

INTERFACE_TEXT_COLOR: ffffffff
INTERFACE_UI_COLOR: 00aaffff

/EquinoxOS
    PROTOCOL: limine
    PATH: boot():/sys/kernel.elf
    MODULE_PATH: boot():/res/font.psf