TIMEOUT: 3
SERIAL: yes
INTERFACE_BRANDING: Equinox OS
INTERFACE_BACKGROUND: boot():/res/BG.BMP
INTERFACE_BACKGROUND_STYLE: stretched
INTERFACE_RESOLUTION: 1024x768
INTERFACE_TEXT_COLOR: ffffffff
INTERFACE_UI_COLOR: 004488ff

/Equinox OS
    PROTOCOL: limine
    PATH: boot():/sys/kernel.elf
    MODULE_PATH: boot():/res/font.psf