timeout: 3
graphics_mode: 1280x720x32
wallpaper: boot():/res/logo.bmp
wallpaper_style: centered

/EquinoxOS
    protocol: limine
    path: boot():/kernel.elf
    module_path: boot():/font.psf
    architecture: x86_64