backdrop: ff0b1220

term_background: ff0b1220
term_foreground: ffffff
term_wallpaper: boot():/res/BG.BMP
wallpaper: boot():/res/BG.BMP

/EquinoxOS
    protocol: limine
    path: boot():/sys/kernel.elf
    module_path: boot():/res/font.psf